### ISSUE TITLE
SPIKE - find a way to get the monorepo run scripts only in modified workspaces

### ISSUE THREAD

**Issue by AlzAmido** [amido/webpack-federated-modules-distributed-ssr#20]
AS A developer
WHEN I make changes to one lib and one app
THEN when I run npm run test from root, it will only run tests in those two apps (not the whole monorepo)

**Comment by urecio** [comment]
Now it's possible to do this on pre-commits via lint-staged and also run a specific command like npm run app-shell:test

**Comment by AlzAmido** [comment]
can you PR this?
