### ISSUE TITLE
SPIKE - do we need yalc?

### ISSUE THREAD

**Issue by AlzAmido** [amido/webpack-federated-modules-distributed-ssr#24]

**Comment by urecio** [comment]
You probably need yalc, but that isn't a tool you will put on a boilerplate. It's just a tool of choice for each developer.
If you want your html tags to resolve to your microfrontends locally, you probably want to yalc them on the main app.
Another solution is to import the microfrontends on the main app via npm 7 and build the entire thing

**Comment by AlzAmido** [comment]
we need to cover a situation where one of the MFE is using a different (older) version of a package so we want to be able to define the version of the package used by a particular consumer. if latest we would obviously symlink with the one in the source code.

**Comment by AlzAmido** [comment]
OUTPUT 
we do not need Yalc -> npm 8 does the following (when running `npm i` at root level):
1) install all packages at root level
2) install all packages at workspaces level (hoisting all common packages and installing deltas into worksopaces' node_modules folder) in the order they are specified in the package.json under "workspaces
3) symlink all "type":"module" workspaces into root level
4) (what we have demonstrated) the symlinking is performed against the hash of the exact version

so when a consumer is requesting a version of a package that is exactly or at least (^) the version of the package we have as a workspace, it will then symlink.
if the version is different, it will keep the symlinked version in the root node_modules (to be consumed by others) whilst installing the specific requested version in the node_module under the consumer.
